apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: piscord
data:
  PORT: "8000"
  MONGO_URI: mongodb://<username>:<password>@mongo.piscord.svc.cluster.local:27017/piscord?authSource=admin
  REDIS_URI: redis://redis.piscord.svc.cluster.local:6379
