apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: piscord
data:
  PORT: "8000"
  MONGO_URI: "mongodb://root:password@mongodb.piscord.svc.cluster.local:27017/piscord?authSource=admin"
