apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: piscord
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # e.g. "root"
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4= # e.g. "password"
