apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: piscord
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== # "root"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # "password"
