apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: piscord
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: <base64_encoded_username> # e.g. "root"
  MONGO_INITDB_ROOT_PASSWORD: <base64_encoded_password> # e.g. "password"
