apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: piscord
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: <base64-encoded-username>
  MONGO_INITDB_ROOT_PASSWORD: <base64-encoded-password>
